

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - observabilidade-net
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    # Porta não exposta publicamente

  mysqld_exporter:
    image: prom/mysqld-exporter:v0.12.1
    container_name: mysqld-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql-db:3306)/"
    command:
      - "--collect.global_status"
      - "--collect.global_variables"
      - "--collect.info_schema.innodb_metrics"
      - "--collect.info_schema.innodb_cmp"
      - "--collect.info_schema.innodb_cmpmem"
      - "--collect.info_schema.processlist"
      - "--collect.info_schema.tables"
      - "--collect.slave_status"
      - "--collect.engine_innodb_status"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9104/"]
      timeout: 10s
      retries: 3
      interval: 30s  
      start_period: 10s
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - observabilidade-net
    ports:
      - "9104:9104" # Expondo para acesso externo

  load-generator:
    build: ./load-generator
    container_name: load-generator
    restart: always
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - observabilidade-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observabilidade-net
    ports:
      - "9090:9090" # Expondo para acesso externo

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    networks:
      - observabilidade-net
    ports:
      - "3300:3000" # Expondo para acesso externo (host 3300 → container 3000)
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:

networks:
  observabilidade-net:
    driver: bridge
